services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - environment/api.dev.env

  db:
    ports:
      - 5432:5432
    image: postgres:alpine
    env_file:
      - environment/api.dev.env
